### ISSUE TITLE
Plot error

### ISSUE THREAD

**Issue by a3020** [bishoph/sopare#58]
When using the '-p' option, the program crashes with an error. This happens in the testing branch:

> INFO:sopare.recorder:start endless recording
INFO:sopare.processing:starting append mode
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:531: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
INFO:sopare.processing:stop append mode because of silence
INFO:sopare.buffering:stop buffering
INFO:sopare.buffering:terminating queue runner
INFO:sopare.recorder:Buffering not alive, stop recording
INFO:sopare.recorder:stop endless recording
Process worker for filtered data:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/pi/Documents/sopare/sopare/worker.py", line 123, in run
    self.analyze.do_analysis(self.compare.get_results(), self.character, self.rawbuf)
  File "/home/pi/Documents/sopare/sopare/analyze.py", line 55, in do_analysis
    matches = self.deep_search(framing, data)
  File "/home/pi/Documents/sopare/sopare/analyze.py", line 91, in deep_search
    word_sim = self.deep_inspection(id, startpos, data)
  File "/home/pi/Documents/sopare/sopare/analyze.py", line 137, in deep_inspection
    sim, sl, sr = self.token_sim(characteristic, dcharacteristic)
  File "/home/pi/Documents/sopare/sopare/analyze.py", line 120, in token_sim
    sim_zcr = self.util.single_similarity(characteristic['zcr'], dcharacteristic['zcr']) * self.cfg.getfloatoption('compare', 'SIMILARITY_ZERO_CROSSING_RATE')
KeyError: 'zcr'
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe

**Comment by bishoph** [comment]
Yes, one option is missing but there is already a pull request available:
https://github.com/bishoph/sopare/pull/55

**Comment by a3020** [comment]
@bishoph Yes, I submitted that PR. But adding the config option with `0` doesn't solve this error.

**Comment by bishoph** [comment]
Ah ok. Will fix this ASAP...stay tuned.

**Comment by bishoph** [comment]
Hmm, with the config option the error does not occur. Make sure to use the config file either with the "-i" option or by changing the default.ini

**Comment by a3020** [comment]
Is there caching going on somewhere? 

I'm checked out in `testing` now, and run `./sopare.py -p`. I don't get the error above. Then I comment the config setting and rerun. Still no error. Then I specify the config file with `-i config/default.ini` and still don't get the error. That's a mystery to me, because that config setting is now missing, so it *should* error out, right?

And just before I posted this, I ran it again (without changing anything) and now I do get the error again...

**Comment by a3020** [comment]
In all cases I get the following error:

> INFO:sopare.recorder:start endless recording
INFO:sopare.processing:starting append mode
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:531: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
INFO:sopare.processing:stop append mode because of silence

**Comment by bishoph** [comment]
There is no caching and you can ignore the INFO messages and the warning. Will take a deeper look to fix the warning though.

**Comment by bishoph** [comment]
Fixed warning with commit 9e5bff9 in testing branch.

**Comment by a3020** [comment]
I tested with your commits, and I don't get an error now before the recording is stopped. However, right after it I still get:

> INFO:sopare.recorder:stop endless recording
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
send(obj)
IOError: [Errno 32] Broken pipe

After the program exits. Does this ring a bell for you?

**Comment by bishoph** [comment]
The different threads and the connecting queues are not in sync when shutting down. Commit b6eae99 should fix this. The used sleep is suboptimal but works for me.

**Comment by a3020** [comment]
I pulled the changes from the `testing` branch, but the same error is still present. Do I need to do anything?

**Comment by bishoph** [comment]
No. Are you using SOPARE with a Raspberry Pi and if so which version?

**Comment by a3020** [comment]
Yes, Raspberry Pi 3 Model B+.

**Comment by bishoph** [comment]
I could delay the queue close function even more but this is nothing I want to do. Will fix this eventually when I have a good idea...

**Comment by a3020** [comment]
@bishoph Fyi, I set the sleep time to `10`, but it's still erroring out. (https://github.com/bishoph/sopare/commit/b6eae99e92b0dfe43a8e8a7b4c48687a59cae9ce#diff-32d135a4421f763f6c488918ce41046dR93)

**Comment by bishoph** [comment]
Ok thx for the info. Are you using a custom config? If yes, please provide it or test with the default one...
